-- Migration 008: Seed Phase Two Initial CMS Content

-- 1. Seed Admission Information (Matching website procedure and requirements)
INSERT INTO `admission_info` (`section_key`, `title`, `subtitle`, `content`, `icon`, `display_order`, `status`) VALUES
('step_1', 'Inquiry & School Visit', 'Step 1 of Admission', 'Contact us via phone, WhatsApp, email, or visit our campus in Kasanje to learn more about our academic programs, school culture, and admission requirements. Our admissions team is delighted to take you on a guided tour of our facilities.', 'help_center', 1, 'published'),
('step_2', 'Application Form', 'Step 2 of Admission', 'Complete the application form either through this website or in person at the school office. Submit required documents including a copy of the pupil\'s birth certificate, 2 recent passport-size photos, and previous school reports.', 'description', 2, 'published'),
('step_3', 'Pupil Assessment', 'Step 3 of Admission', 'Your child will undergo a simple, friendly assessment to help our academic team understand their current learning level and ensure they are placed in the most appropriate class to thrive.', 'person_search', 3, 'published'),
('step_4', 'Enrollment & Fees', 'Step 4 of Admission', 'Upon acceptance, confirm enrollment by completing the necessary registration formalities, paying school fees at our partner banks, and receiving your child\'s requirements checklist and uniform guidelines.', 'check_circle', 4, 'published'),
('requirements', 'General Admission Requirements', 'What every applicant needs', '<p>St. Monica Junior School admits pupils without distinction of race, nationality, or religious background. Requirements include:</p><ul><li>Completed and signed Application Form</li><li>Copy of Birth Certificate or Immunization Card (for Nursery)</li><li>Original or verified copy of the most recent School Report Card</li><li>2 recent passport-size color photographs of the child</li><li>Copy of Parent / Guardian National ID or Passport</li></ul>', 'fact_check', 5, 'published'),
('fees_note', 'School Fees Policy', 'Transparent and structured', '<p>Our tuition and boarding fees are structured to provide premium learning and welfare at competitive rates. Fees are payable before the start of each term via school bank accounts or mobile money merchant codes. Contact the school bursar for detailed fee structures per class level.</p>', 'payments', 6, 'published')
ON DUPLICATE KEY UPDATE `title` = VALUES(`title`);

-- 2. Seed Testimonials (from existing website)
INSERT INTO `testimonials` (`name`, `role`, `child_info`, `rating`, `content`, `photo`, `initials`, `display_order`, `status`) VALUES
('Mrs. Mary Kisakye', 'Parent', 'Parent, Primary 5', 5, 'St Monica has been a blessing to our family. The teachers are caring and dedicated, and my daughter has flourished academically and socially.', NULL, 'MK', 1, 'published'),
('Mr. John Musoke', 'Parent', 'Parent, Primary 3', 5, 'The holistic approach to education here is outstanding. My son not only excels in academics but has also developed strong values and character.', NULL, 'JM', 2, 'published'),
('Mrs. Sarah Nambi', 'Parent', 'Parent, Primary 6', 5, 'Excellent school with modern facilities and passionate teachers. We couldn\'t have chosen a better school for our children.', NULL, 'SN', 3, 'published')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- 3. Seed Sample Admissions for demonstration
INSERT INTO `admissions` (`application_number`, `parent_name`, `mobile`, `email`, `pupil_name`, `pupil_class`, `location`, `message`, `status`, `admin_notes`) VALUES
('SM-2026-0001', 'David Kigozi', '+256 701 234567', 'david.kigozi@example.com', 'Grace Nakimera Kigozi', 'Primary 4', 'Kasanje Town Council, Wakiso', 'Seeking admission for Term 1. Grace is transferring from Entebbe and loves mathematics and music.', 'Under Review', 'Parent contacted for assessment date on Sep 22.'),
('SM-2026-0002', 'Florence Namubiru', '+256 772 987654', 'florence.namubiru@gmail.com', 'Brian Ssenyonjo', 'Top Class', 'Mpigi District', 'Applying for Top Class nursery. Very active child, interested in day scholar program.', 'New', NULL),
('SM-2026-0003', 'Dr. Patrick Mukasa', '+256 752 555123', 'p.mukasa@hospital.org', 'Angel Mukasa', 'Primary 1', 'Bwebajja, Entebbe Road', 'Angel completed top class with excellent reading skills. We are excited to join the St. Monica family.', 'Accepted', 'Assessment passed with Distinction. Admission letter issued.')
ON DUPLICATE KEY UPDATE `application_number` = VALUES(`application_number`);

-- 4. Seed SEO Settings for all key pages
INSERT INTO `seo_settings` (`page_key`, `page_title`, `meta_title`, `meta_description`, `meta_keywords`, `og_title`, `og_description`, `canonical_url`) VALUES
('homepage', 'Homepage', 'St. Monica Junior School Kasanje — Quality Primary & Nursery Education', 'St. Monica Junior School Kasanje is a premier private mixed day and boarding nursery and primary school located in Wakiso District, Uganda. Inspiring excellence and integrity.', 'St Monica Junior School, Kasanje, Wakiso schools, primary school Uganda, nursery school Wakiso', 'St. Monica Junior School Kasanje — Always Aim Higher', 'A leading educational institution in Uganda dedicated to academic excellence, moral integrity, and holistic child development.', 'https://stmonicakasanje.ac.ug/'),
('about', 'About Us', 'About Us — St. Monica Junior School Kasanje', 'Learn about our history, mission, vision, core values, and dedicated administration at St. Monica Junior School Kasanje.', 'about St Monica, school history, vision mission, school values', 'About St. Monica Junior School', 'Discover our heritage, core values, and commitment to nurturing responsible future leaders.', 'https://stmonicakasanje.ac.ug/about.html'),
('academics', 'Academics', 'Academic Programs & Excellence — St. Monica Junior School', 'Explore academic excellence, curriculum, classroom activities, and holistic educational programs at St. Monica Junior School.', 'academics, primary curriculum Uganda, PLE results, nursery education', 'Academic Programs — St. Monica Junior School', 'Providing quality education with a balanced and holistic curriculum designed for exceptional child development.', 'https://stmonicakasanje.ac.ug/academics.html'),
('curriculum', 'Curriculum', 'National & Practical Curriculum — St. Monica Junior School', 'Our comprehensive curriculum balances the Uganda National Curriculum with practical skills, STEM, languages, and moral education.', 'Uganda curriculum, primary syllabus, literacy numeracy, practical learning', 'Curriculum — St. Monica Junior School', 'A robust curriculum designed to foster critical thinking, creativity, and moral discipline.', 'https://stmonicakasanje.ac.ug/curriculum.html'),
('cocurricular', 'Co-curricular', 'Sports & Co-curricular Activities — St. Monica Junior School', 'Discover sports, music, dance, drama, scouting, and clubs that enrich pupil life outside the classroom.', 'school sports, MDD, scouting, debate club, swimming, athletics', 'Co-curricular Activities at St. Monica', 'Empowering pupils through sports, cultural arts, leadership clubs, and active teamwork.', 'https://stmonicakasanje.ac.ug/cocurricular.html'),
('gallery', 'Media Gallery', 'School Photo & Activity Gallery — St. Monica Junior School', 'View photos of campus life, graduation ceremonies, sports galas, academic exhibitions, and school events.', 'St Monica photos, gallery, graduation pictures, sports day, campus tour', 'Photo Gallery — St. Monica Junior School', 'Moments of joy, learning, and celebration at St. Monica Junior School Kasanje.', 'https://stmonicakasanje.ac.ug/gallery.html'),
('contact', 'Contact Us', 'Contact & Admissions Office — St. Monica Junior School Kasanje', 'Get in touch with St. Monica Junior School. Inquire about admissions, schedule a campus visit, or locate us in Kasanje, Wakiso.', 'contact school, admissions inquiry, school location Wakiso, phone email', 'Contact St. Monica Junior School', 'We welcome inquiries from prospective parents and partners. Reach out to our admissions office today.', 'https://stmonicakasanje.ac.ug/contact.html')
ON DUPLICATE KEY UPDATE `page_title` = VALUES(`page_title`);
