-- Migration 020: Add Status-Specific Email Templates for Admissions
INSERT INTO `email_templates` (`template_key`, `label`, `subject`, `body_html`) VALUES
('application_status_accepted', 'Application Status: Accepted', 'Congratulations! {{pupil_name}}\'s Admission Application Accepted — {{application_number}}', '<p>Dear {{parent_name}},</p><p>We are delighted to inform you that your admission application for <strong>{{pupil_name}}</strong> to join <strong>{{pupil_class}}</strong> at <strong>{{school_name}}</strong> has been <strong>ACCEPTED</strong>!</p><div style="background:#f0fdf4; border:1px solid #bbf7d0; padding:15px; border-radius:8px; margin:16px 0;"><p style="margin:0 0 8px 0; color:#166534; font-weight:bold;">Admission Summary:</p><ul style="margin:0; padding-left:20px; color:#15803d;"><li><strong>Application Reference:</strong> {{application_number}}</li><li><strong>Pupil Name:</strong> {{pupil_name}}</li><li><strong>Admitted Class:</strong> {{pupil_class}}</li><li><strong>Status:</strong> Accepted</li></ul></div>{{custom_message}}<p><strong>Next Steps:</strong></p><ol><li>Please visit the school administration office in Kasanje to collect your child\'s official Admission Letter and Requirements List.</li><li>Confirm enrollment and complete registration formalities with the school registrar.</li><li>Settle the required admission and tuition fees through our partner banks or mobile money before the term begins.</li></ol><p>If you have any questions or need guidance, please feel free to reach out to us at <strong>{{school_phone}}</strong> or reply to this email at <strong>{{school_email}}</strong>.</p><p>Once again, congratulations and welcome to the {{school_name}} family!</p><p>Warm regards,<br><strong>Admissions Office</strong><br>{{school_name}}</p>'),

('application_status_under_review', 'Application Status: Under Review', 'Application Under Review: {{pupil_name}} — {{application_number}}', '<p>Dear {{parent_name}},</p><p>Thank you for choosing <strong>{{school_name}}</strong> for your child\'s education.</p><p>We would like to let you know that the admission application for <strong>{{pupil_name}}</strong> applying for <strong>{{pupil_class}}</strong> (Application #<strong>{{application_number}}</strong>) is currently <strong>UNDER REVIEW</strong> by our academic and admissions committee.</p><div style="background:#fffbeb; border:1px solid #fef3c7; padding:15px; border-radius:8px; margin:16px 0;"><p style="margin:0; color:#92400e;"><strong>Current Status:</strong> Under Review<br>Our team is verifying documents and evaluating classroom vacancies for {{pupil_class}}.</p></div>{{custom_message}}<p>Our admissions office may contact you regarding scheduling a pupil assessment or requesting any supplementary documents. You will receive an update once a decision has been finalized.</p><p>For urgent inquiries, please contact us at <strong>{{school_phone}}</strong> or <strong>{{school_email}}</strong>.</p><p>Best regards,<br><strong>Admissions Committee</strong><br>{{school_name}}</p>'),

('application_status_contacted', 'Application Status: Contacted / Follow-up', 'Admissions Follow-up regarding {{pupil_name}} — {{application_number}}', '<p>Dear {{parent_name}},</p><p>This is a follow-up from the admissions office at <strong>{{school_name}}</strong> regarding application #<strong>{{application_number}}</strong> for <strong>{{pupil_name}}</strong> ({{pupil_class}}).</p><div style="background:#eff6ff; border:1px solid #bfdbfe; padding:15px; border-radius:8px; margin:16px 0;"><p style="margin:0; color:#1e40af;"><strong>Status:</strong> Contacted / Action Required<br>Our admissions team reached out or is requesting a brief follow-up regarding your application.</p></div>{{custom_message}}<p>Please call or WhatsApp our admissions team at <strong>{{school_phone}}</strong> or reply to <strong>{{school_email}}</strong> during office hours (Monday - Friday: 8:00 AM - 5:00 PM) to confirm details or arrange an assessment date.</p><p>Thank you,<br><strong>Admissions Office</strong><br>{{school_name}}</p>'),

('application_status_rejected', 'Application Status: Not Accepted', 'Update on Admission Application {{application_number}} — {{pupil_name}}', '<p>Dear {{parent_name}},</p><p>Thank you for your interest in <strong>{{school_name}}</strong> and for giving us the opportunity to consider <strong>{{pupil_name}}</strong> for admission into <strong>{{pupil_class}}</strong> (Application #<strong>{{application_number}}</strong>).</p><p>Due to classroom capacity limitations and a very high volume of applications for {{pupil_class}} this term, we regret to inform you that we are unable to offer an admission placement for {{pupil_name}} at this time.</p>{{custom_message}}<p>Your child\'s application will be retained on our active waiting list. Should a place become available, our admissions team will notify you promptly.</p><p>We wish {{pupil_name}} all the best in their academic journey and future pursuits.</p><p>Sincerely,<br><strong>Admissions Committee</strong><br>{{school_name}}</p>'),

('application_status_withdrawn', 'Application Status: Withdrawn', 'Application Withdrawn — {{application_number}} ({{pupil_name}})', '<p>Dear {{parent_name}},</p><p>This email confirms that admission application #<strong>{{application_number}}</strong> for <strong>{{pupil_name}}</strong> (Class: {{pupil_class}}) has been marked as <strong>WITHDRAWN</strong> in our records.</p>{{custom_message}}<p>If this withdrawal was requested by you, no further action is required. If you believe this status change was made in error or wish to reinstate the application, please contact our admissions office as soon as possible at <strong>{{school_phone}}</strong> or <strong>{{school_email}}</strong>.</p><p>Kind regards,<br><strong>Admissions Office</strong><br>{{school_name}}</p>')

ON DUPLICATE KEY UPDATE `label` = VALUES(`label`), `subject` = VALUES(`subject`), `body_html` = VALUES(`body_html`);
